# Generated by Django 4.2.29 on 2026-03-04 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='---------', max_length=9)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('x_wins', 'X Wins'), ('o_wins', 'O Wins'), ('draw', 'Draw'), ('abandoned', 'Abandoned')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_x', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('player_symbol', models.CharField(default='X', max_length=1)),
                ('board', models.CharField(default='---------', max_length=9)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('status', models.CharField(default='active', max_length=20)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_games',
            },
        ),
    ]
